/**
 * SharePoint list titles (Site Assets app).
 * Run CyberEffortsTracker.listFields('<ListTitle>') in the console to verify internal names.
 */
window.CyberEffortsTracker = window.CyberEffortsTracker || {};

CyberEffortsTracker.CONFIG = {
  /** Set only if lists live on a different web than this page (e.g. site collection root). */
  siteWebUrl: null,
  lists: {
    projects: 'CyberEffortsTrackerProjectsList',
    submissions: 'CyberEffortsTrackerSubmissionsList',
    effortLog: 'CyberEffortsTrackerEffortLogList',
    notes: 'CyberEffortsTrackerNotesList',
    changeLog: 'CyberEffortsTrackerChangeLogList',
  },
  timezone: 'Asia/Riyadh',
  pageSize: 5000,
  /** Official RAG palette (computed status — never user-edited) */
  ragColors: {
    Red: { hex: '#DC2626', bg: 'bg-red-100', text: 'text-red-800', ring: 'ring-red-200' },
    Amber: { hex: '#D97706', bg: 'bg-amber-100', text: 'text-amber-900', ring: 'ring-amber-200' },
    Green: { hex: '#059669', bg: 'bg-emerald-100', text: 'text-emerald-800', ring: 'ring-emerald-200' },
    Grey: { hex: '#64748B', bg: 'bg-slate-100', text: 'text-slate-700', ring: 'ring-slate-200' },
  },
  ragOrder: ['Red', 'Amber', 'Green', 'Grey'],
  /** Status donut (not RAG) — blocked/on hold use Amber/Grey hints */
  statusChartColors: {
    Active: '#059669',
    'Pending kickoff': '#64748B',
    'Blocked-client': '#D97706',
    'On hold': '#64748B',
    Closed: '#94A3B8',
    'Not awarded': '#94A3B8',
  },
  choices: {
    stage: [
      'Pre-Concept',
      'Concept',
      'Schematic Design',
      'Detailed Design',
      'IFC',
      'Tender',
      'Supervision',
      'Gap Assessment',
      'Other',
    ],
    status: [
      'Active',
      'Pending kickoff',
      'Blocked-client',
      'On hold',
      'Closed',
      'Not awarded',
    ],
    cyberProvisioned: ['Yes', 'No', 'Pending', 'Not assessed'],
    rag: ['Red', 'Amber', 'Green', 'Grey'],
    submissionType: [
      'CMP',
      'Concept Report',
      '30% SD',
      '50% SD',
      '60% SD',
      '100% SD',
      'DD',
      '90% DD',
      '100% DD',
      'IFC',
      'TRA',
      'Design Review',
      'Tender Evaluation',
      'Spec Review',
      'Other',
    ],
    submissionStatus: ['Planned', 'In progress', 'Submitted', 'Cancelled'],
    noteCategory: ['Client', 'Internal', 'Risk', 'Decision'],
    changeSourceList: ['Projects', 'Submissions', 'EffortLog', 'Notes'],
  },
  /** Override if your list uses different internal names */
  fields: {
    projects: {
      projectNumber: 'ProjectNumber',
      title: 'Title',
      client: 'Client',
      stage: 'Stage',
      status: 'Status',
      statusReason: 'StatusReason',
      blockedSince: 'BlockedSince',
      cyberProvisioned: 'CyberProvisioned',
      cyberPM: 'CyberPM',
      dssPM: 'DSS_PM',
      projectPM: 'ProjectPM',
      budgetMM: 'BudgetMM',
      nextSubmissionDate: 'NextSubmissionDate',
      nextSubmissionType: 'NextSubmissionType',
      rag: 'RAG',
      latestNote: 'LatestNote',
    },
    submissions: {
      project: 'Project',
      projectId: 'ProjectId',
      type: 'Type',
      description: 'Description',
      plannedDate: 'PlannedDate',
      actualDate: 'ActualDate',
      submissionStatus: 'SubmissionStatus',
      owner: 'Owner',
      reference: 'Reference',
    },
    effortLog: {
      project: 'Project',
      projectId: 'ProjectId',
      month: 'Month',
      person: 'Person',
      mmConsumed: 'MMConsumed',
    },
    notes: {
      project: 'Project',
      projectId: 'ProjectId',
      noteDate: 'NoteDate',
      author: 'Author',
      category: 'Category',
      text: 'Text',
    },
    changeLog: {
      projectNumber: 'ProjectNumber',
      sourceList: 'SourceList',
      itemId: 'ItemID',
      itemLabel: 'ItemLabel',
      field: 'Field',
      oldValue: 'OldValue',
      newValue: 'NewValue',
      changeType: 'ChangeType',
      changedOn: 'ChangedOn',
      changedBy: 'ChangedBy',
      suppressed: 'Suppressed',
    },
  },
  trackedFields: {
    Projects: [
      'Stage',
      'Status',
      'StatusReason',
      'CyberProvisioned',
      'CyberPM',
      'DSS_PM',
      'ProjectPM',
      'BudgetMM',
      'Client',
      'Title',
    ],
    Submissions: ['Type', 'PlannedDate', 'ActualDate', 'SubmissionStatus', 'Owner'],
    EffortLog: ['MMConsumed'],
    Notes: [],
  },
};
